name: Hello World

on:
  push:
    branches:
      - main

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Print This is the first demo action file for testing
        run: echo "This is the first demo action file for testing"
